language : node_js
node_js :
 - stable
install:
 - npm install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
 before_deploy:
  - sed -i '/.nyc_output/d' .gitignore
  - sed -i '/coverage/d' .gitignore
  - npm test    
